spring:
  application:
    name: spring-data-demo-1
  datasource:
    password: 1
    url: jdbc:postgresql://127.0.0.1:5432/spring-data-demo
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  sql:
    init:
      mode: always
logging:
  level:
    root: info
server:
  port: 8080